### PR TITLE
support for sequences inside braces in namespecs

### PR DESCRIPTION
**Pull request by burrbull**
See https://pypi.org/project/braceexpand/ and https://stackoverflow.com/questions/22996645/brace-expansion-in-python-glob

### CODE REVIEW

**Review by adamgreig — APPROVED** [review]
Looks good. I guess this is also in the new svdtools?

bors merge

**Comment by adamgreig** [comment]
Ah, you'll need to format it before CI passes, using `black`.

**Comment by burrbull** [comment]
> Ah, you'll need to format it before CI passes, using `black`.

I try, but my version of `black` doesn't see any problem. Do it yourself, please.

**Review by adamgreig — APPROVED** [review]
Sorry, looks like the failing CI was the isort check after black. I've fixed it.

bors merge

**Pull request merged**
