### PR TITLE
Bump to v0.1.6

### PR DESCRIPTION
**Pull request by MabezDev**
I believe this is all that is required for a new release?

### CODE REVIEW

**Comment by jessebraham** [comment]
Sorry to be a bother but it appears I had forgotten to update `CHANGELOG.md` in b9c100a28e4cf4ac94b8d4e9c2eb88c76f550d18, would you by any chance be able to add that as well please?
I can then merge this (although I'm not sure if it automatically releases on PyPi or not either, honestly).

**Comment by MabezDev** [comment]
Done :)

**Comment by MabezDev** [comment]
Seeing as it still hasn't updated, I'm guessing @nickray has to push it to PyPi?

**Comment by nickray** [comment]
Yep me or agg can publish currently.

**Comment by MabezDev** [comment]
Perfect, thank you!

**Pull request merged**
