### PR TITLE
Enable bors

### PR DESCRIPTION
**Pull request by adamgreig**
This PR enables [bors](https://bors.tech) for svdtools.

As configured, everyone with push access (me and @nickray) can approve PRs, but I'm very happy to add anyone else interested -- @jessebraham @MabezDev?

### CODE REVIEW

**Comment by adamgreig** [comment]
bors try

**Comment by jessebraham** [comment]
I'd be more than happy to help out

**Comment by MabezDev** [comment]
Sure!

**Comment by adamgreig** [comment]
@jessebraham @MabezDev great, thanks! I've added you both to the bors reviewers list so you should be able to `bors r+` any (approved) PR to get it merged. And you can approve any PR.

Could one of you approve and r+ this PR to test it out?

**Comment by MabezDev** [comment]
Okay, here it goes!

bors r+

**Pull request merged**
