### PR TITLE
Change 'version' command to '--version' option

### PR DESCRIPTION
**Pull request by adamgreig**
Click has a built-in `version_option()` we can use instead of having a custom `version` command. Additionally I've bumped `VERSION` to 0.1.5 since that's what's on PyPI... I don't know why `master` here doesn't have 0.1.5 when PyPI does, any ideas @nickray?

### CODE REVIEW

**Comment by nickray** [comment]
- I'd rather keep the `version` subcommand, this is quite popular (and user friendly). Happy to add the option `--version` too of course (good to have multiple ways to do the first things one might want to do with a tool). The philosophy is that options should always be optional (contrast to positional mandatory arguments, and subcommands). At least that's what I was planning when I started this.

- Looks like I only have the v0.1.5 commit locally, sorry!

What's missing:

- CHANGELOG entry:
```
## [v0.1.5] 2020-03-20

* Manipulate multiple peripheral address blocks - @arjanmels
```

- `git tag -a 0.1.5 -m'v0.1.5'`

I'm not familiar yet with Bors, does that replace this kind of manual approach?

**Comment by adamgreig** [comment]
> I'd rather keep the version subcommand

Sure, I've restored it in a new commit to this PR.

> Looks like I only have the v0.1.5 commit locally, sorry!

I guess it can't be pushed onto the current master, shall I just update the CHANGELOG entry in this PR too, or do you want to rebase/merge your commit on? We can tag the result either way.

> I'm not familiar yet with Bors, does that replace this kind of manual approach?

Bors only manages merging PRs but nothing to do with releases.

**Comment by nickray** [comment]
I rebased my leftover commit onto this. Looks good to merge to me.

**Comment by adamgreig** [comment]
Thanks, LGTM too. Do you want to approve the PR and then `bors r+` it?

**Comment by nickray** [comment]
Eh?

**Comment by adamgreig** [comment]
Ah, some sort of bors-github issue I noticed earlier on rust-embedded repos too, you can see the logs [here](https://app.bors.tech/repositories/23731/log) (or via going to bors.tech); for now I'd just retry...

bors r=nickray

**Pull request merged**
