### PR TITLE
mmaps derivedFrom markers

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by adamgreig** [comment]
Thanks for this PR! I think it might be clearer if registers were handled the same as peripherals - print out all the fields of the register it's derived from, instead of just marking what it's derived from (it may be hard for someone to even look up the name/path of the derivation). But, I don't know how easy it is to find the parent register, I couldn't work it out very quickly.

**Comment by burrbull** [comment]
It is definitely not easy. I think this task is not worth the time you can spent on it

**Review by adamgreig — APPROVED** [review]
Thanks, fair enough. Let's go with this for now anyway.

bors r+

**Comment by burrbull** [comment]
bors retry

**Comment by burrbull** [comment]
bors r=@adamgreig

**Comment by adamgreig** [comment]
bors retry

**Pull request merged**
