### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by MabezDev**
Add a basic travis config to patch the `esp32` & `stm32` crates to guard against breaking changes.

Should hopefully stop changes like #13 from breaking crates.

### CODE REVIEW

**Comment by MabezDev** [comment]
This *should* good to go. I had a little trouble with `language: "python"` (for some reasons pip wasn't installed in venv?) so I switched to rust and installed python after.

**Comment by nickray** [comment]
Nice, it spotted said issue :) Will rollback and see if this picks up on it.

**Comment by nickray** [comment]
@MabezDev can you rebase on master to see if it all works?

**Comment by MabezDev** [comment]
It now works for stm32, obviously this breaks esp32 but hopefully I'll be able to find a way around that.

**Comment by nickray** [comment]
I'd like to merge this, can you comment out the esp32 call for now?

**Comment by MabezDev** [comment]
@nickray Sorry I didn't get a chance to look at this earlier. Instead of commenting it out, I've separated the jobs and set esp32 as allowed to fail for now.

**Comment by nickray** [comment]
Perfect, thanks a lot!

**Pull request merged**
