### PR TITLE
ignore if not exists

### LINKED ISSUE #67: Ignore missing registers
My question is about this check:
https://github.com/stm32-rs/svdtools/blob/d8521cd0dc0314365097edcac75ccbb1fa19864c/svdtools/patch.py#L1037-L1038

Is it necessary those checks to be hard error?
It is often particular chips don't have some registers. And we need to create individual rule for them which complicates all patch system.
I'd prefer this check be just warning saying "Rule ignored: register not found". Or something like this.

### PR DESCRIPTION
**Pull request by burrbull**
Closes #67

### CODE REVIEW

**Comment by adamgreig** [comment]
I like the idea, but I'm not totally sure about the syntax. Maybe it's OK, but I worry it will look too confusing, or might be mixed up for a real start of a rule. Could you add it to the README too as an example?

Maybe another option is a "_missing_ok: True" field. It can't be used everywhere, but I think it could be used anywhere that we want to patch something and it might not exist.

**Comment by burrbull** [comment]
> Maybe another option is a "_missing_ok: True" field. It can't be used everywhere, but I think it could be used anywhere that we want to patch something and it might not exist.

Adding option is not ok because there is not always an a hash, sometimes there is also an array or nothing.

**Comment by burrbull** [comment]
Yet one argument against `_missing_ok` is `yaml_includes`.
Now we merge entries with identical names during include (if you ask me it is now the biggest issue of current system as it changes sequence of patch rules). The best solution would be not merge them at all. But this is not easy to implement.

**Comment by burrbull** [comment]
cc @Emilgardis @kossnikita do you have any thoughts/suggestions?

**Comment by kossnikita** [comment]
I don't like `_missing_ok`. It is not clear where it should be used and how to disable it. I would like to see it as an argument. But in the case when you need to allow this behavior for a specific patch, I would prefer the original option proposed by @burrbull .

**Comment by burrbull** [comment]
What should it be? Suffix or prefix? And what sequence of symbols is better?

**Comment by burrbull** [comment]
Tilde maybe?
`"?~SPEC"`
Looks clearer.

**Comment by kossnikita** [comment]
Is it possible to do this regex-like [abc] or [a,b,c]?
```yaml
"[TIM[18],TIM20]":
```

**Comment by burrbull** [comment]
> Is it possible to do this regex-like [abc] or [a,b,c]?
> 
> ```yaml
> "[TIM[18],TIM20]":
> ```
> 
> or
> 
> ```yaml
> "(TIM[18],TIM20)?":
> ```
> 
> EDIT: It is more correct to use `*` rather than `?` if do it like in regex

It is possible to check both prefix and suffix, but I don't like it:
1. We already use a lot of `?` and `*` at the end of spec when matching arrays and similar things. This is why I prefer `prefix` then `suffix`.
2. This extended spec can be passed to `is_match` accidentally. `svdtools` should stop with error in such situation. So it should not be correct match syntax.
3. Matches uses [`glob`](https://docs.rs/globset) syntax, not `regex`. Less powerful, but less messy. Mixing does not look a good idea.

**Comment by kossnikita** [comment]
> Matches uses [`glob`](https://docs.rs/globset) syntax, not `regex`.

Sorry, I'm new and don't know that much about crates. This clarifies a lot for me. Then the prefix seems to be the best solution. `?~` or `?@` doesn't matter to me.

**Comment by burrbull** [comment]
Merging.

**Pull request merged**
