### PR TITLE
release rust svdtools-0.2.5

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Review by adamgreig — APPROVED** [review]
bors r+

**Comment by adamgreig** [comment]
bors retry

**Comment by adamgreig** [comment]
The CI check should run `apt-get update` before `apt-get install xmllint`, which _might_ be part of why it's failing here, could you add that to this PR please?

**Comment by burrbull** [comment]
Fixed :smile:

**Comment by adamgreig** [comment]
bors retry

**Pull request merged**
