### PR TITLE
Fix typerror

### PR DESCRIPTION
**Pull request by jannic**

### CODE REVIEW

**Review by adamgreig — APPROVED** [review]
thanks!

bors r+

**Comment by adamgreig** [comment]
Looks like the rp2040 build is still failing.

**Comment by jannic** [comment]
Yes:
```
[ERROR svd2rust] Error rendering device
    
    Caused by:
        0: Rendering error at peripheral
           Name: DMA
           Description: DMA with separate read and write masters
           Group: No group name
        1: register CH0_CTRL_TRIG not found
```

This didn't happen in my local tests, because the locally installed version of svd2rust was 0.25.0. Now that I upgraded to 0.25.1,  I get the same error message. I'll try to find and fix the cause.

**Comment by jannic** [comment]
Looks like some ill interaction between `_cluster` and other patches on the same element in `rp2040.yaml`. Not sure what's the exact reason and how to fix it. However, it doesn't seem to be related to this PR. So let's keep the rp2040 CI check disabled for now.

**Review by adamgreig — APPROVED** [review]
bors r+

**Pull request merged**
